export interface CodeInfo {
  code_type: string;
  code_name: string;
  code_key: string;
  code_value_ko: string;
  code_value_en: string;
}

export interface CodeResponse {
  result_info: CodeInfo[];
  code_info: any | null;
}

export interface ThumbnailInfo {
  row_num?: number | null;
  prev_idx?: number | null;
  prev_title?: string | null;
  prev_writer?: string | null;
  prev_date?: string | null;
  next_idx?: number | null;
  next_title?: string | null;
  next_writer?: string | null;
  next_date?: string | null;
  use_yn?: string | null;
  del_yn: string;
  show_yn?: string | null;
  open_yn?: string | null;
  user_idx: number;
  view_count?: number | null;
  user_name_ko: string;
  user_name_en: string;
  reg_user_idx: number;
  reg_user_name_ko: string;
  reg_user_name_en: string;
  reg_dttm: string;
  mod_user_idx?: number | null;
  mod_user_name_ko?: string | null;
  mod_user_name_en?: string | null;
  mod_dttm?: string | null;
  file_idx: number;
  type_idx: number;
  file_uuid?: string | null;
  origin_type: string;
  origin_type_cd: string;
  dir_type: string;
  dir_type_cd: string;
  file_type: string;
  file_type_cd: string;
  content_type: string;
  file_ext: string;
  file_size: string;
  file_name: string;
  file_name_enc: string;
  file_path: string;
  file_path_enc: string;
  file_content?: string | null;
}

export interface ArtistListResultInfo {
  row_num: number;
  prev_idx?: number | null;
  prev_title?: string | null;
  prev_writer?: string | null;
  prev_date?: string | null;
  next_idx?: number | null;
  next_title?: string | null;
  next_writer?: string | null;
  next_date?: string | null;
  use_yn?: string | null;
  del_yn: string;
  show_yn: string;
  open_yn?: string | null;
  user_idx?: number | null;
  view_count?: number | null;
  user_name_ko?: string | null;
  user_name_en?: string | null;
  reg_user_idx: number;
  reg_user_name_ko: string;
  reg_user_name_en: string;
  reg_dttm: string;
  mod_user_idx: number;
  mod_user_name_ko: string;
  mod_user_name_en: string;
  mod_dttm: string;
  people_idx: number;
  people_type: string;
  people_type_cd: string;
  name_first_ko: string;
  name_ko: string;
  name_last_ko: string;
  name_first_cn?: string | null;
  name_cn?: string | null;
  name_last_cn?: string | null;
  name_first_en: string;
  name_last_en: string;
  name_en: string;
  email?: string | null;
  gender: string;
  gender_cd: string;
  birth_type?: string | null;
  birth_type_cd?: string | null;
  birth_yyyy?: string | null;
  birth_mm?: string | null;
  birth_dd?: string | null;
  birth?: string | null;
  inter_phone_number: string;
  mobile1?: string | null;
  mobile2?: string | null;
  mobile3?: string | null;
  mobile?: string | null;
  people_memo_ko: string;
  people_memo_en: string;
  main_show_yn: string;
  sort_num: number;
  profile_info?: string | null;
  work_info?: string | null;
  file_info?: string | null;
  thumbnail_info?: ThumbnailInfo[];
  file_content?: string | null;
  file_path_enc?: string | null;
  file_name_org?: string | null;
  qr_img: string;
}

export interface ArtistResponse {
  result_info: ArtistListResultInfo[];
}

export interface FileInfo {
  row_num: number | null;
  prev_idx: number | null;
  prev_title: string | null;
  prev_writer: string | null;
  prev_date: string | null;
  next_idx: number | null;
  next_title: string | null;
  next_writer: string | null;
  next_date: string | null;
  use_yn: string | null;
  del_yn: string;
  show_yn: string | null;
  open_yn: string | null;
  user_idx: number;
  view_count: number | null;
  user_name_ko: string | null;
  user_name_en: string | null;
  reg_user_idx: number;
  reg_user_name_ko: string;
  reg_user_name_en: string;
  reg_dttm: string;
  mod_user_idx: number | null;
  mod_user_name_ko: string | null;
  mod_user_name_en: string | null;
  mod_dttm: string | null;
  file_idx: number;
  type_idx: number;
  file_uuid: string | null;
  origin_type: string;
  origin_type_cd: string;
  dir_type: string;
  dir_type_cd: string;
  file_type: string | null;
  file_type_cd: string;
  content_type: string;
  file_ext: string;
  file_size: string;
  file_name: string;
  file_name_enc: string;
  file_path: string;
  file_path_enc: string;
  file_content: string | null;
}

export interface PageInfo {
  page_num: number;
  page_size: number;
  size: number;
  start_row: number;
  end_row: number;
  pages: number;
  total: number;
  pre_page: number;
  next_page: number;
  is_first_page: boolean;
  is_last_page: boolean;
  has_previous_page: boolean;
  has_next_page: boolean;
  navigate_pages: number;
  navigatepage_nums: number[];
  navigate_first_page: number;
  navigate_last_page: number;
}

export interface GallertListResultInfo {
  postType: string;
  postStatus: string;
  row_num: number;
  prev_idx: number | null;
  prev_title: string | null;
  prev_writer: string | null;
  prev_date: string | null;
  next_idx: number | null;
  next_title: string | null;
  next_writer: string | null;
  next_date: string | null;
  use_yn: string | null;
  del_yn: string;
  show_yn: string;
  open_yn: string;
  user_idx: number | null;
  view_count: number;
  user_name_ko: string | null;
  user_name_en: string | null;
  reg_user_idx: number;
  reg_user_name_ko: string;
  reg_user_name_en: string;
  reg_dttm: string;
  mod_user_idx: number;
  mod_user_name_ko: string;
  mod_user_name_en: string;
  mod_dttm: string;
  work_idx: number;
  people_idx: number;
  name_first_ko: string;
  name_ko: string;
  name_last_ko: string;
  name_first_cn: string | null;
  name_cn: string | null;
  name_last_cn: string | null;
  name_first_en: string;
  name_last_en: string;
  name_en: string;
  people_type: string | null;
  people_type_cd: string | null;
  people_memo_ko: string | null;
  people_memo_en: string | null;
  main_title_ko: string;
  main_title_en: string;
  sub_title_ko: string;
  sub_title_en: string;
  paint_type: string;
  post_type_cd: string;
  post_status_cd: string;
  paint_type_cd: string;
  paint_type_show_yn: string;
  art_type: string;
  art_type_cd: string;
  art_type_show_yn: string;
  participate_type: string;
  participate_type_show_yn: string;
  participate_type_cd: string;
  participate_memo_ko: string | null;
  participate_memo_en: string | null;
  currency_type: string;
  currency_type_cd: string;
  price_info_ko: string;
  price_info_en: string;
  price_info_show_yn: string;
  size_info_ko: string;
  size_info_en: string;
  size_info_show_yn: string;
  materials_info_ko: string;
  materials_info_en: string;
  materials_info_show_yn: string;
  year_info_ko: string;
  year_info_en: string;
  year_info_show_yn: string;
  place_info_ko: string | null;
  place_info_en: string | null;
  place_info_show_yn: string;
  content_info_ko: string;
  content_info_en: string;
  work_link: string | null;
  work_memo_ko: string | null;
  work_memo_en: string | null;
  work_pwd: string | null;
  file_info: FileInfo[];
  thumbnail_info: FileInfo[];
  file_content: string | null;
  qr_img: string;
}

export interface GallertListApiResponse {
  page_info: PageInfo;
  result_info: GallertListResultInfo[];
}

export interface GallertDtlApiResponse {
  page_info: PageInfo;
  result_info: GalleryDtlResultInfo[];
}

export interface Board {
  boardIdx: number;
  userIdx: number;
  channelType?: string;
  importantType?: string;
  processStatus?: string;
  detailType?: string;
  categoryType?: string;
  subjectKo: string;
  subjectEn: string;
  subTitleKo?: string;
  subTitleEn?: string;
  contentKo: string;
  contentEn: string;
  securityCode?: string;
  showYn: "Y" | "N";
  openYn: "Y" | "N";
  boardPwd?: string;
  alimYn?: string;
  userNameFirstKo: string;
  userNameLastKo: string;
  userNameFirstEn: string;
  userNameLastEn: string;
  localYn?: string;
  email: string;
  gender?: string;
  birthYyyy?: string;
  birthMm?: string;
  birthDd?: string;
  interPhoneNumber?: string;
  mobile1: string;
  mobile2?: string;
  mobile3?: string;
  mobileAgency?: string;
  fileContent?: string;
  userNameKo?: string;
  userNameEn?: string;
  regUserIdx: number;
  regUserNameKo?: string;
  regUserNameEn?: string;
  modUserIdx: number;
  modUserNameKo?: string;
  modUserNameEn?: string;
  modDttm?: string;
  commentType: string;
  targetIdx: number;
}

export interface GalleryDtlFileInfo {
  file_idx: number;
  type_idx: number;
  origin_type: string;
  origin_type_cd: string;
  dir_type: string;
  dir_type_cd: string;
  file_type: string | null;
  file_type_cd: string;
  content_type: string;
  file_ext: string;
  file_size: string;
  file_name: string;
  file_name_enc: string;
  file_path: string;
  file_path_enc: string;
}

export interface GalleryDtlResultInfo {
  postType: string;
  postStatus: string;
  prev_idx: number;
  prev_title: string;
  prev_writer: string;
  prev_date: string;
  next_idx: number;
  next_title: string;
  next_writer: string;
  next_date: string;
  del_yn: string;
  show_yn: string;
  open_yn: string;
  view_count: number;
  reg_user_idx: number;
  reg_user_name_ko: string;
  reg_user_name_en: string;
  reg_dttm: string;
  mod_user_idx: number;
  mod_user_name_ko: string;
  mod_user_name_en: string;
  mod_dttm: string;
  work_idx: number;
  people_idx: number;
  name_ko: string;
  name_en: string;
  people_type: string;
  people_type_cd: string;
  people_memo_ko: string;
  people_memo_en: string;
  main_title_ko: string;
  main_title_en: string;
  paint_type: string;
  post_type_cd: string;
  post_status_cd: string;
  paint_type_cd: string;
  paint_type_show_yn: string;
  art_type: string;
  art_type_cd: string;
  art_type_show_yn: string;
  participate_type: string;
  participate_type_cd: string;
  participate_type_show_yn: string;
  currency_type: string;
  currency_type_cd: string;
  price_info_ko: string;
  price_info_en: string;
  price_info_show_yn: string;
  size_info_ko: string;
  size_info_en: string;
  size_info_show_yn: string;
  materials_info_ko: string;
  materials_info_en: string;
  materials_info_show_yn: string;
  year_info_ko: string;
  year_info_en: string;
  year_info_show_yn: string;
  place_info_ko: string | null;
  place_info_en: string | null;
  place_info_show_yn: string;
  content_info_ko: string;
  content_info_en: string;
  work_link: string | null;
  work_memo_ko: string;
  work_memo_en: string;
  work_pwd: string | null;
  file_info: FileInfo[];
  thumbnail_info: FileInfo[];
  qr_img: string;
}

export interface CommentInfo {
  use_yn: string;
  del_yn: string;
  show_yn: string;
  open_yn: string;
  user_idx: number;
  view_count: number;
  user_name_ko: string;
  user_name_en: string;
  reg_user_idx: number;
  reg_user_name_ko: string;
  reg_user_name_en: string;
  reg_dttm: string;
  mod_user_idx: number;
  mod_user_name_ko: string;
  mod_user_name_en: string;
  mod_dttm: string;
  board_idx: number;
  comment_idx: number;
  board_ref: number;
  board_ref_order: number;
  board_step: number;
  target_idx: number;
  comment_count: number;
  comment_type_cd: string;
  comment_type: string;
  board_type: string;
  board_type_cd: string;
  category_type: string;
  category_type_cd: string;
  process_status: string;
  process_status_cd: string;
  subject_ko: string;
  subject_en: string;
  sub_title_ko: string;
  sub_title_en: string;
  content_ko: string;
  content_en: string;
  alim_yn: string;
  important_type: string;
  important_type_cd: string;
  board_pwd: string;
  user_name_first_ko: string;
  user_name_last_ko: string;
  user_name_first_en: string;
  user_name_last_en: string;
  local_yn: string;
  email: string;
  gender: string;
  gender_cd: string;
  birth_yyyy: string;
  birth_mm: string;
  birth_dd: string;
  inter_phone_number: string;
  mobile1: string;
  mobile2: string;
  mobile3: string;
  mobile_agency: string;
  mobile_agency_cd: string;
  file_info: any;
  child_comments: string[];
}

export interface WorkInfo {
  postType: string;
  postStatus: string;
  row_num: number;
  prev_idx: number;
  prev_title: string;
  prev_writer: string;
  prev_date: string;
  next_idx: number;
  next_title: string;
  next_writer: string;
  next_date: string;
  use_yn: string;
  del_yn: string;
  show_yn: string;
  open_yn: string;
  user_idx: number;
  view_count: number;
  user_name_ko: string;
  user_name_en: string;
  reg_user_idx: number;
  reg_user_name_ko: string;
  reg_user_name_en: string;
  reg_dttm: string;
  mod_user_idx: number;
  mod_user_name_ko: string;
  mod_user_name_en: string;
  mod_dttm: string;
  work_idx: number;
  people_idx: number;
  name_first_ko: string;
  name_ko: string;
  name_last_ko: string;
  name_first_cn: string;
  name_cn: string;
  name_last_cn: string;
  name_first_en: string;
  name_last_en: string;
  name_en: string;
  people_type: string;
  people_type_cd: string;
  people_memo_ko: string;
  people_memo_en: string;
  main_title_ko: string;
  main_title_en: string;
  sub_title_ko: string;
  sub_title_en: string;
  paint_type: string;
  post_type_cd: string;
  post_status_cd: string;
  paint_type_cd: string;
  paint_type_show_yn: string;
  art_type: string;
  art_type_cd: string;
  art_type_show_yn: string;
  participate_type: string;
  participate_type_show_yn: string;
  participate_type_cd: string;
  participate_memo_ko: string;
  participate_memo_en: string;
  currency_type: string;
  currency_type_cd: string;
  price_info_ko: string;
  price_info_en: string;
  price_info_show_yn: string;
  size_info_ko: string;
  size_info_en: string;
  size_info_show_yn: string;
  materials_info_ko: string;
  materials_info_en: string;
  materials_info_show_yn: string;
  year_info_ko: string;
  year_info_en: string;
  year_info_show_yn: string;
  place_info_ko: string;
  place_info_en: string;
  place_info_show_yn: string;
  content_info_ko: string;
  content_info_en: string;
  work_link: string;
  work_memo_ko: string;
  work_memo_en: string;
  work_pwd: string;
  file_info: FileInfo[];
  thumbnail_info: ThumbnailInfo[];
  file_content: string;
  qr_img: string;
  qr_type: string;
  qr_type_cd: string;
}

export interface UserInfo {
  row_num: number;
  prev_idx: number;
  prev_title: string;
  prev_writer: string;
  prev_date: string;
  next_idx: number;
  next_title: string;
  next_writer: string;
  next_date: string;
  use_yn: string;
  del_yn: string;
  show_yn: string;
  open_yn: string;
  user_idx: number;
  view_count: number;
  user_name_ko: string;
  user_name_en: string;
  reg_user_idx: number;
  reg_user_name_ko: string;
  reg_user_name_en: string;
  reg_dttm: string;
  mod_user_idx: number;
  mod_user_name_ko: string;
  mod_user_name_en: string;
  mod_dttm: string;
  people_idx: number;
  people_type: string;
  people_type_cd: string;
  name_first_ko: string;
  name_ko: string;
  name_last_ko: string;
  name_first_cn: string;
  name_cn: string;
  name_last_cn: string;
  name_first_en: string;
  name_last_en: string;
  name_en: string;
  email: string;
  gender: string;
  gender_cd: string;
  birth_type: string;
  birth_type_cd: string;
  birth_yyyy: string;
  birth_mm: string;
  birth_dd: string;
  birth: string;
  inter_phone_number: string;
  mobile1: string;
  mobile2: string;
  mobile3: string;
  mobile: string;
  people_memo_ko: string;
  people_memo_en: string;
  main_show_yn: string;
  sort_num: number;
  profile_info: ProfileInfo[];
  work_info: WorkInfo[];
  file_info: FileInfo[];
  thumbnail_info: ThumbnailInfo[];
  file_content: string;
  file_path_enc: string;
  file_name_org: string;
  qr_img: string;
  qr_type: string;
  qr_type_cd: string;
}

export interface ProfileInfo {
  row_num: number;
  prev_idx: number;
  prev_title: string;
  prev_writer: string;
  prev_date: string;
  next_idx: number;
  next_title: string;
  next_writer: string;
  next_date: string;
  use_yn: string;
  del_yn: string;
  show_yn: string;
  open_yn: string;
  user_idx: number;
  view_count: number;
  user_name_ko: string;
  user_name_en: string;
  reg_user_idx: number;
  reg_user_name_ko: string;
  reg_user_name_en: string;
  reg_dttm: string;
  mod_user_idx: number;
  mod_user_name_ko: string;
  mod_user_name_en: string;
  mod_dttm: string;
  profile_type: string;
  profile_type_cd: string;
  profile_content_ko: string;
  profile_content_en: string;
}

export interface ArtistDtlResultInfo {
  row_num: number | null;
  prev_idx: number;
  prev_title: string;
  prev_writer: string;
  prev_date: string;
  next_idx: number;
  next_title: string;
  next_writer: string;
  next_date: string;
  use_yn: string | null;
  del_yn: string;
  show_yn: string;
  open_yn: string | null;
  user_idx: number | null;
  view_count: number | null;
  user_name_ko: string | null;
  user_name_en: string | null;
  reg_user_idx: number;
  reg_user_name_ko: string;
  reg_user_name_en: string;
  reg_dttm: string;
  mod_user_idx: number;
  mod_user_name_ko: string;
  mod_user_name_en: string;
  mod_dttm: string;
  people_idx: number;
  people_type: string;
  people_type_cd: string;
  name_first_ko: string | null;
  name_ko: string;
  name_last_ko: string;
  name_first_cn: string | null;
  name_cn: string | null;
  name_last_cn: string | null;
  name_first_en: string;
  name_last_en: string;
  name_en: string;
  email: string | null;
  gender: string;
  gender_cd: string;
  birth_type: string | null;
  birth_type_cd: string | null;
  birth_yyyy: string | null;
  birth_mm: string | null;
  birth_dd: string | null;
  birth: string | null;
  inter_phone_number: string;
  mobile1: string | null;
  mobile2: string | null;
  mobile3: string | null;
  mobile: string | null;
  people_memo_ko: string;
  people_memo_en: string;
  main_show_yn: string;
  sort_num: number;
  profile_info: ProfileInfo[];
  work_info: WorkInfo[];
  file_info: FileInfo[];
  thumbnail_info: ThumbnailInfo[];
  file_content: string | null;
  file_path_enc: string | null;
  file_name_org: string | null;
  qr_img: string;
  qr_type: string;
  qr_type_cd: string;
}

export interface ArtistDtlResponse {
  result_info: ArtistDtlResultInfo;
  code_info: any | null;
}
