export interface ProfileInfo {
  rowNum: number | null;
  prevIdx: number | null;
  prevTitle: string;
  prevWriter: string;
  prevDate: string;
  nextIdx: number | null;
  nextTitle: string;
  nextWriter: string;
  nextDate: string;
  useYn: string;
  delYn: string;
  showYn: string;
  userIdx: number | null;
  userNameKo: string;
  userNameEn: string;
  regUserIdx: number;
  regUserNameKo: string;
  regUserNameEn: string;
  regDttm: string;
  modUserIdx: number | null;
  modUserNameKo: string;
  modUserNameEn: string;
  modDttm: string;
  profileType: string;
  profileTypeCd: string;
  profileContent: string;
}

export interface FileInfo {
  rowNum: number | null;
  prevIdx: number | null;
  prevTitle: string;
  prevWriter: string;
  prevDate: string;
  nextIdx: number | null;
  nextTitle: string;
  nextWriter: string;
  nextDate: string;
  useYn: string;
  delYn: string;
  showYn: string;
  userIdx: number;
  userNameKo: string;
  userNameEn: string;
  regUserIdx: number;
  regUserNameKo: string;
  regUserNameEn: string;
  regDttm: string;
  modUserIdx: number | null;
  modUserNameKo: string;
  modUserNameEn: string;
  modDttm: string;
  fileIdx: number;
  typeIdx: number;
  fileUuid: string;
  originType: string;
  originTypeCd: string;
  dirType: string;
  dirTypeCd: string;
  fileType: string;
  fileTypeCd: string;
  contentType: string;
  fileExt: string;
  fileSize: string;
  fileNameOrg: string;
  fileNameEnc: string;
  filePath: string;
  filePathEnc: string;
  fileContent: string | null;
}

export interface ResultInfo {
  rowNum: number | null;
  prevIdx: number | null;
  prevTitle: string;
  prevWriter: string;
  prevDate: string;
  nextIdx: number | null;
  nextTitle: string;
  nextWriter: string;
  nextDate: string;
  useYn: string;
  delYn: string;
  showYn: string;
  userIdx: number | null;
  userNameKo: string;
  userNameEn: string;
  regUserIdx: number;
  regUserNameKo: string;
  regUserNameEn: string;
  regDttm: string;
  modUserIdx: number;
  modUserNameKo: string;
  modUserNameEn: string;
  modDttm: string;
  peopleIdx: number;
  categoryParentIdx: number;
  categoryParentDiv: string;
  categoryParentDivCd: string;
  categoryParentNameKo: string;
  categoryParentNameCn: string;
  categoryParentNameEn: string;
  categoryParentMemo: string;
  categoryChildIdx: number;
  categoryChildDiv: string;
  categoryChildDivCd: string;
  categoryChildNameKo: string;
  categoryChildNameCn: string;
  categoryChildNameEn: string;
  categoryChildMemo: string;
  peopleType: string;
  peopleTypeCd: string;
  nameFirstKo: string;
  nameKo: string;
  nameLastKo: string;
  nameFirstCn: string;
  nameCn: string;
  nameLastCn: string;
  nameFirstEn: string;
  nameLastEn: string;
  nameEn: string;
  email: string;
  gender: string;
  genderCd: string;
  birthType: string;
  birthTypeCd: string;
  birthYyyy: string;
  birthMm: string;
  birthDd: string;
  birth: string;
  interPhoneNumber: string;
  mobile1: string;
  mobile2: string;
  mobile3: string;
  mobile: string;
  peopleMemo: string;
  mainShowYn: string;
  sortNum: number;
  profileInfo: ProfileInfo[];
  fileInfo: FileInfo[];
  fileContent: string | null;
  filePathEnc: string | null;
  fileNameOrg: string | null;
  categoryType: string;
}